"""create device and telemetry tables

Revision ID: 9e5327ba18df
Revises:
Create Date: 2026-09-04 12:52:04.884846

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9e5327ba18df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
