"""create device

Revision ID: d71ef4c61a18
Revises: 9e5327ba18df
Create Date: 2026-09-04 13:02:07.536911

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d71ef4c61a18"
down_revision: str | Sequence[str] | None = "9e5327ba18df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.alter_column(
            "device_key",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=150),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.alter_column(
            "device_key",
            existing_type=sa.String(length=150),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
